# Generated by Django 5.0.4 on 2024-05-24 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_services_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services_images/service_details')),
                ('description', models.CharField(max_length=1000)),
                ('status', models.BooleanField(default=False, help_text='0-show, 1-Hidden')),
                ('techstack', models.CharField(max_length=1000)),
                ('languages_used', models.CharField(max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='app.services')),
            ],
        ),
    ]
