# Generated by Django 5.0.4 on 2024-05-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_service_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_detail',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
