# Generated by Django 5.0.4 on 2024-05-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_service_detail_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_detail',
            name='slug',
        ),
        migrations.AddField(
            model_name='services',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
