# Generated by Django 5.0.4 on 2024-05-26 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_service_detail_slug_services_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='slug',
        ),
    ]
